spring:
  datasource:
      url: jdbc:mysql://localhost:3306/example?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
mybatis:
   mapperLocations: classpath:/mapper/*.xml
